Reading doc and some discussion
chalk-lab/Mooncake.jl pull request #220
Opened 2024-08-09 07:55 UTC by sunxd3

2024-09-04 09:54 UTC, willtebbutt requested changes
Basically happy with your proposals -- only a couple of things I disagree with.

2024-09-04 09:54 UTC, willtebbutt commented on docs/src/algorithmic_differentiation.md
> +A special case is: obtaining the gradient (of scalar output) correcponds to when ``Q = 1``, by letting ``\bar{y} = 1``.
Could we stick with the original wording here?

2024-09-04 09:54 UTC, willtebbutt commented on docs/src/algorithmic_differentiation.md
> +There are a couple of aspects of `f` which require thoughts:
```suggestion
There are a couple of aspects of `f` which require thought:
```
I'm pretty sure the original wording is correct (grammatically speaking)

2024-09-04 10:00 UTC, willtebbutt commented
Regarding your questions:

>  should s be included in this?

Almost certainly. We should fix this. I think I re-worked the example, but must have forgotten to update this bit.

>  these are not quite obvious to me

Could you expand one which bit is not clear?

>  any update to this?

Not yet, although I really need to push it forward. I think this is also how JAX thinks about these kinds of objects, so I might take a closer look at what they do.

>  maybe mention this is for demonstration, in the sense that Tapir will generate this automatically? (if I understand right)

Great point. Would you mind adding something to this effect?

2024-09-04 11:27 UTC, sunxd3 commented on docs/src/mathematical_interpretation.md
> +f((x, y, z, s)) = ((x, y, x \odot y, \text{Ref}(2 x \odot y)), (2 x \odot y, \sum_{d=1}^D x \odot y))
not sure this is standard (or even correct)

2024-09-04 11:29 UTC, sunxd3 commented on docs/src/mathematical_interpretation.md
> +        &= \langle \bar{y}_1, \dot{x} \rangle + \langle D \varphi [x]^\ast (\bar{y}_2), \dot{x} \rangle \nonumber \quad \text{(by definition of the adjoint)} \\
I think I was confused because I missed the `*` for adjoint at first read, so I added an extra step, hope this make sense

2024-09-04 11:32 UTC, sunxd3 commented on docs/src/mathematical_interpretation.md
> +Tapir.jl will generate `rrule!!`s of similar effect (mostly) automatically, but it is good to see a manual implementation for understanding.
also made an addition here (just for visibility)

2024-09-05 15:14 UTC, willtebbutt commented on docs/src/mathematical_interpretation.md
> +        &= \langle \bar{y}_1, \dot{x} \rangle + \langle D \varphi [x]^\ast (\bar{y}_2), \dot{x} \rangle \nonumber \quad \text{(by definition of the adjoint)} \\
This is great -- much clearer now

2024-09-05 15:17 UTC, willtebbutt commented on docs/src/mathematical_interpretation.md
> +Tapir.jl will generate `rrule!!`s of similar effect (mostly) automatically, but it is good to see a manual implementation for understanding.
I like this. I think I'd like to re-word very slightly to:
```suggestion
This hand-written implementation is to aid your understanding -- Tapir.jl should be relied upon to generate this code automatically in practice.
```

2024-09-05 15:20 UTC, willtebbutt commented on docs/src/mathematical_interpretation.md
> +f((x, y, z, s)) = ((x, y, x \odot y, \text{Ref}(2 x \odot y)), (2 x \odot y, \sum_{d=1}^D x \odot y))
Nearly -- you can drop the `Ref` (we've not given `Ref` a mathematical interpreteration):
```julia
f((x, y, z, s)) = ((x, y, x \odot y, 2 x \odot y), (2 x \odot y, \sum_{d=1}^D x \odot y))
```

2024-09-05 15:21 UTC, willtebbutt commented
Thanks for the updated items -- think we're nearly there!

2024-09-06 05:43 UTC, sunxd3 commented on docs/src/mathematical_interpretation.md
> +f((x, y, z, s)) = ((x, y, x \odot y, \text{Ref}(2 x \odot y)), (2 x \odot y, \sum_{d=1}^D x \odot y))
```suggestion
f((x, y, z, s)) = ((x, y, x \odot y, 2 x \odot y), (2 x \odot y, \sum_{d=1}^D x \odot y))
```

2024-09-06 09:08 UTC, willtebbutt approved these changes
This is a really helpful PR, thanks!

2024-09-06 09:09 UTC, merged